### PR TITLE
v1.500 Cyrillic Pro expansion

### PR DESCRIPTION
**Pull request by alexeiva**
Hi Pablo, 
This update adds support for GF Cyrillic Pro, and adds missing glyphs within GF Latin Pro.

cc @davelab6 @m4rc1e

### CODE REVIEW

**Comment by HBelusca** [comment]
The ReactOS operating-system project (which incorporates the Libre-Franklin font) would have its look in cyrillic greatly improved if this PR is considered:
https://jira.reactos.org/browse/CORE-14906

**Comment by moyogo** [comment]
@StefanPeev How does your branch differ from this?

**Comment by StefanPeev** [comment]
> 
> 
> @StefanPeev How does your branch differ from this?
@moyogo 

My branch is not up to date. I stopped working on the Libre Franklin Thin when I realized that Cyrillic would be developed by Alexei Vanyashin. Maybe Vanyashin used my version as the basis, but there are significant differences in the layout of a number of Cyrillic glyphs (especially Cyrillic „к“, „ж“ - in Vanyashin's version they look more Russian and less international but it is only my personal opinion). On the other hand there is Bulgarian letterform model in my project included as local feature for BGR. @davelab6 Dave Crossland suggested me to expand this letterform model and to offer it for including in the Vanyashin's version. If another does not do this, I will probably try to suggest this model next year.

**Comment by JapanYoshi** [comment]
Is there any advancement on Libre Franklin Cyrillic?

**Comment by alexeiva** [comment]
Hi @impallari 
would you consider merging this?

**Comment by alexeiva** [comment]
@emmamarichal Can we push this Cyrillic update to production?

**Comment by emmamarichal** [comment]
@alexeiva, yes sure! You can send a PR to that repo: https://github.com/googlefonts/Libre-Franklin
I have an access to it, and I can do the QA. Feel free to open an issue here so we can track this upgrade: https://github.com/google/fonts/issues/new/choose, and tag me in :)

**Pull request merged**
