### PR TITLE
Cyrillic for Libre-Fraklin

### PR DESCRIPTION
**Pull request by StefanPeev**
FontForge source file for LibreFranklin-Thin with Basic Cyrillic and
local Cyrillic for Bulgarian, Serbian, Macedonian.

### CODE REVIEW

**Comment by StefanPeev** [comment]
@impallari @davelab6 @crystaltype Please have a look at LibreFranklin-Thin with GF Cyrillic Plus support.
Cc @alexeiva

**Comment by davelab6** [comment]
Alexei please take a look

**Comment by alexeiva** [comment]
I Inspected the performance in text. There are issues with proportions and metrics that need more work. This is not ready to be merged yet.
screen shot 2017-02-14 at 7 49 46 pm

Having two project reviews in line I cannot inspect this in more depth at the moment. A few of the design issues:

Pennant (top part) of `б` too short, off balance. 
screen shot 2017-02-14 at 7 56 57 pm

Right-side descenders not defined enought (too short) in glyph group:
screen shot 2017-02-14 at 7 57 14 pm


Glyphs `пц` not compensated in width. Should be narrower than `н`

screen shot 2017-02-14 at 7 57 17 pm

Treatment of diagonal is not in accord with font style:

screen shot 2017-02-14 at 7 57 21 pm

`я` Bowl is too smal. Corelate with `ь`

screen shot 2017-02-14 at 7 57 20 pm


Glyph set coverage:

Google Core > Full support
Google Cyrillic Plus missing:
```
hryvnia
tenge 
tugrik
```

Localised glyphs. Missing Chuvash and Bashkir localised variants:

```
Ghestroke-cy.loclBSH
ghestroke-cy.loclBSH
Zedescender-cy.loclBSH
zedescender-cy.loclBSH
Esdescender-cy.loclBSH
esdescender-cy.loclBSH
Esdescender-cy.loclCHU
esdescender-cy.loclCHU
```

**Comment by StefanPeev** [comment]
@davelab6 @alexeiva Thank you! I'll do the corrections and will prepare next PR.

**Comment by davelab6** [comment]
(You can leave this one open and push your updates into it, rather than
make a new PR)

**Comment by StefanPeev** [comment]
@davelab6 OK! I'll leave it open...

**Comment by StefanPeev** [comment]
I'm preparing an updated to LibreFranklin-Thin. It's not finalized yet but I hope it's going in the right direction: resolving the issues with proportions, metrics and glyph set coverage also. Here is a preview.

librefranklin_02

**Comment by jeditobe** [comment]
We need cyrillic support!

**Comment by jeditobe** [comment]
ReactOS project depends on you

**Comment by davelab6** [comment]
@alexeiva plenty review in November :)

**Comment by jeditobe** [comment]
Hey-hey, Cyrillic support every day!

**Comment by jeditobe** [comment]
Still no updates on this?

**Pull request closed without merging**
