### PR TITLE
Vietnamese

### PR DESCRIPTION
**Pull request by crystaltype**
Due to the confusion with github it said that this branch is 1 commit behind yours but I actually used the v1004, so no worries. I've added colors to the glyphs I make changes for review. Thank you!

### CODE REVIEW

**Comment by davelab6** [comment]
This branch is 1 commit behind; Pablo added a 1.004 file, and that is in conflict with the one that you added. 

You need to run 

```
git rebase -i
```

and then mark the first commit as 'drop' so its forgotten and then force push your branch; since the PR reflects the branch, then this will say 'no conflicts' :)

**Comment by impallari** [comment]
Don't worry, I can upgrade the files manually.
First I want to have a quick look at the files, just to make sure everything is Ok.

**Comment by impallari** [comment]
Mmmm.. I spotted a few problems so far...

1) Uppercase Vietnamese diacritics will be cropped, as they exceed the 1004 BBox top limit
screen shot 2016-07-07 at 18 12 18

2) The Latin accents are now way too low, and they look really bad for non-Vietnamese.

3) Some of the Vietnamese accent are not interpolating properly, for example:
screen shot 2016-07-07 at 18 17 41

4) Also side-bearings seems weird... 
screen shot 2016-07-07 at 18 18 24
screen shot 2016-07-07 at 18 20 47

**Comment by crystaltype** [comment]
Thank you Pablo, and sorry for my inexperience with glyphs.
- Wew, about the vertical metrics, if we can't change it, the only way is to decrease the size of all the stacked diacritics and creat inconsistency, which is not very good. But we can do this, it'd take me much longer to do a master though.
- About the interpolating multiple master error, I'm not familiar with glyphs alogrithm so what could be the problem I did wrong?
- About the sizebearings of the accents, I'll fix it.

**Comment by davelab6** [comment]
Pablo how far do you think the vertical metrics can change?

Maybe it needs to be scaled on the body..?

**Comment by impallari** [comment]
The vertical metrics are already as big as possible, and I will really hate to see the font scaled down. What about using .case diacritics for the uppercase?

**Comment by davelab6** [comment]
> The vertical metrics are already as big as possible

It could be that we change the vertical metrics, and allow for ink beyond them, that will be clipped in some software but not in all. 

> I will really hate to see the font scaled down. 

OK :) 

> What about using .case diacritics for the uppercase?

I think that's fine

**Comment by crystaltype** [comment]
We can use the .case diacritics, yes. But the original distance between the accent and the x-height is really high, it looks weird in Vietnamese if we keep it that way. You know, the stacked diacritics have to be as tight as possible. So do you think we can lower the accents down a little bit, maybe not as far as I moved them down but about half of that distance?

**Comment by impallari** [comment]
Can we leave the Latin as they are and only move down the Vietnamese ones? Does that makes any sense?

**Comment by andjc** [comment]
If you just change the Vietnamese combinations, then there will be a mismatch between Vietnamese and non-Vietnamese base character + diacritic combinations.

Myabe an alternative would be to use "locl" to which would alllow more than one approach to the diacritics based on language system tags ... so dflt and VIT

**Comment by khaledhosny** [comment]
You need to only change the win metrics to avoid cropping, insisting that win metrics be exactly the same as typo metrics is counter intuitive here.

**Comment by davelab6** [comment]
@khaledhosny yes, I think that can work - @kalapi is going to look into it :)

**Comment by impallari** [comment]
I will close this and start filling issues in Nhung's fork: https://github.com/crystaltype/Libre-Franklin
Will later merge manually.

Cheers,
Pablo

**Comment by impallari** [comment]
Reopening, since "Issues" are disabled in Nhung's fork. Will be adding issues here in the meantime.

**Comment by impallari** [comment]
In Nhung's v1.006 Thin:
- /Abreve jumps down, and the height becomes inconsistent with other diacritics.
  output_x3zooj
  Also inconsistent with other uppercase also having breve
  screen shot 2016-08-04 at 5 50 20
  Everything else seems OK in the Thin master

**Comment by impallari** [comment]
In Nhung's v1.006 Black:
- Also inconsistent with other uppercases having breve
  screen shot 2016-08-04 at 5 54 02
- In the Thin master all other accent remained in place, while in the Black master many accent jumps up and down.
  I don't have any problem if you move up the Vietnamese-related diacritics, but you should also move ALL the other diacritics accordingly. If not, the remaining ones will stay low and will look miss-aligned.
  blackaccentjumps

**Comment by crystaltype** [comment]
Thank you for your feedback!
I've moved them back, please check out the lastest commit, I think everything should be ok now.

**Comment by davelab6** [comment]
@impallari ping

**Comment by impallari** [comment]
I will close this and continue in the latest Pull Request thread, here https://github.com/impallari/Libre-Franklin/pull/11

**Pull request closed without merging**
